### ISSUE TITLE
Adopt Publish to BCR Github App

### ISSUE THREAD

**Issue by tshaynik** [tweag/rules_sh#36]
**Is your feature request related to a problem? Please describe.**
At the moment, it is necessary to manually make a pull request to the Bazel Central Repository GitHub repo to add a new release to the BCR. It would be nice to automate this process, so creating a release in this repo will automatically publish to the BCR.

**Describe the solution you'd like**

Adopt the "Publish to BCR" Github App to automate the process of publishing a release to the BCR.
https://github.com/bazel-contrib/publish-to-bcr

**Describe alternatives you've considered**
- continue manually opening PRs on the BCR
- Write a custom CI script to publish to the BCR on tag

**Additional context**

**Comment by tshaynik** [comment]
I made a [Tweag fork of the BCR](https://github.com/tweag/bazel-central-registry) and made a request to add the Publish to BCR App to rules_sh.

**Comment by aherrmann** [comment]
@tshaynik Thank you!

> I made a [Tweag fork of the BCR](https://github.com/tweag/bazel-central-registry)

Could you write here why the fork is needed for posterity?

> and made a request to add the Publish to BCR App to rules_sh.

Thanks! According to the settings the app is installed on this repository.

**Comment by tshaynik** [comment]
Could you write here why the fork is needed for posterity?
@aherrmann With the Publish to BCR app installed, a tag on this repository will automatically commit the new version to our fork of the BCR repo and open a PR from there to the main BCR repo.

The last step is to add template files. https://github.com/bazel-contrib/publish-to-bcr/tree/main/templates

I'll aim to make a PR for that today.
