### ISSUE TITLE
Create a BCR test module

### ISSUE THREAD

**Issue by avdv** [tweag/rules_sh#41]
**Is your feature request related to a problem? Please describe.**
The tests define additional repositories which are used throughout the test run. Also, the tests require a Java toolchain.

We don't want to declare these repositories / dependencies in our module when published to the BCR and other users depend on it. Currently, that is the reason we do not run any tests on the BCR, ie. using `-@rules_sh//tests/...` to exclude any tasks from the sub-packages in test. See https://github.com/bazelbuild/bazel-central-registry/pull/151/files#diff-69436317cfb1c71c170452cbfff407ecd8a334035282d8e3c62eeb480a08dbb6

**Describe the solution you'd like**
Add a BCR test module which can be exercised in the BCR CI pipeline. See https://github.com/bazelbuild/bazel-central-registry/blob/main/docs/README.md?rgh-link-date=2023-01-24T08%3A07%3A04Z#test-module

**Describe alternatives you've considered**
Alternatively, we might create a tarball out of the sources, not including the test sources and attach this artifact to the releases. E.g. bazel-skylib does it like this, see https://github.com/bazelbuild/bazel-skylib/blob/main/distribution/BUILD.

**Additional context**

**Comment by z8v** [comment]
@aherrmann @avdv I believe we can close this now that #44 is merged.
